### ISSUE TITLE
Problems with units

### ISSUE THREAD

**Issue by Biffen1** [richb1/FIBARO-Official-SmartThings-Device-Handlers#16]
Hi, I have a Fibaro plug EU FGWPF-102 ZW5. When power is turned on does the power meter change to GW instead of W. As the consumption is low is the consequence that it only show 0.0. I use the Device handler that is provided as default in Smartthings. Is there a problem with the DH or a setting issue, total energy consumption show Wh which is appropriate in my case

**Comment by Biffen1** [comment]
After some use has the units now corrected themselves consumption now W and total consumption kWh... Strange

**Comment by slootzky** [comment]
Hey @Biffen1 , how did you fix it?
